### ISSUE TITLE
Bilibili插件2.1.1无法更新视频

### ISSUE THREAD

**Issue by RogerRordo** [yajuhua/podcast2#11]
很好的项目，先给大佬点个赞！

主版本：2.3.2
Bilibili插件版本：2.1.1
现象：up发布了新视频，从podcast2日志看更新完成，但没有发现新视频并进行下载。**Bilibili插件退回到2.1.0后问题解决。**

另外，我在localStorage中找不到ac_time_value，我是随便填了个0的，2.1.0也能正常使用，但不知道这个会不会是导致2.1.1不可用的原因。

**Comment by yajuhua** [comment]
![Snipaste_2024-07-13_22-09-53](https://github.com/user-attachments/assets/4883ea22-5e92-4a3e-a686-c3b14675464f)
ac_time_value和cookie都要填

**Comment by RogerRordo** [comment]
看来确实是因为ac_time_value没填。没填也能用，但很快就会失效。不过很奇怪，我之前试了好多次登录都获取不到ac_time_value，今天登录获取到了。总之感谢大佬了，close了~

**Comment by yajuhua** [comment]
目前可以在线提取了[https://b-login.vercel.app](https://b-login.vercel.app)
