### ISSUE TITLE
下载视频内容出错

### ISSUE THREAD

**Issue by kennywhat** [yajuhua/podcast2#12]
在podcast客户端下载视频节目时提示“节目下载有误，详细情况查看服务”。在后台“下载 | 上传错误”页面也可看到错误的提示，但“详细”里面没有介绍错误的原因。

音频类内容无出现类似错误。

**Comment by yajuhua** [comment]
发一下podcast2版本和插件名称版本

**Comment by yajuhua** [comment]
“详细”也截图看看

**Comment by yajuhua** [comment]
“详细”也截图看看

**Comment by kennywhat** [comment]
podcast2的版本是v2.3.2

目前只装了两个插件
-youtube.com  2.2.0
-youtube  2.0.5

补充一个现象：在“正在下载”页面，可以看到视频下载的任务，而且进度是可以去到100%的，但结果就去到“下载 | 上传错误”那里了。

![Snipaste_2024-07-13_22-25-37](https://github.com/user-attachments/assets/4e9a49f3-e82e-4dd6-a4aa-b20ae9bf4f7e)

![Snipaste_2024-07-13_22-29-21](https://github.com/user-attachments/assets/101dcd8d-00d4-4a1c-aee9-61c0fa9b47e4)

**Comment by yajuhua** [comment]
1.你把所有订阅都删除
2.删除youtube.com 2.2.0和youtube 2.0.5这两个插件
3.只安装youtube.com 2.2.0这一个
4.再试试

**Comment by kennywhat** [comment]
> 1.你把所有订阅都删除 2.删除youtube.com 2.2.0和youtube 2.0.5这两个插件 3.只安装youtube.com 2.2.0这一个 4.再试试

感谢！按着方法好了。
