### ISSUE TITLE
插件列表始终无法刷新出来

### ISSUE THREAD

**Issue by zhq837git** [yajuhua/podcast2#13]
请问插件有其他下载的地方吗？插件列表始终无法刷新出来

**Comment by yajuhua** [comment]
- 1.有没有报错，有的话提供下日志
- 2.试一下浏览器能不能打开 [插件仓库链接](https://plugin-podcast2.pages.dev/metadata.json)
- 3.[下载插件](https://github.com/yajuhua/generate-plugin-metadata-action/tree/master/v2)，不过直接上传插件未必能用
- 4.如果还不行，那你加下企鹅群方便回复
