### ISSUE TITLE
希望增加播放列表（合集），以及视频过滤器bug

### ISSUE THREAD

**Issue by deyangchu** [yajuhua/podcast2#14]
1. 希望能和podsync一样可以支持播放列表（在b站里叫合集）和单个视频的订阅~
2. 另外在现有只能订阅整个频道的情况下我尝试了使用视频描述关键词筛选特定播放列表的内容，但似乎设置的视频描述关键词会错误地应用于视频名称过滤器，应该是个可以快速修复的bug
3. 最后如果能更全面地自定义生成的订阅的标题、描述和封面图片的话就太棒了！

**Comment by yajuhua** [comment]
目前是支持修改订阅的标题和封面图片，但还不支持修改描述。为了方便回复建议加一下企鹅群，这里回复比较麻烦。
