### ISSUE TITLE
B站下载下来的视频有声音，但画面是全黑

### ISSUE THREAD

**Issue by kennywhat** [yajuhua/podcast2#15]
RT

**Comment by yajuhua** [comment]
提供一下链接，建议加入企鹅群方便交流

**Comment by kennywhat** [comment]
好啊，群号哪里可以找到？

**Comment by yajuhua** [comment]
945797272

**Comment by kennywhat** [comment]
我怀疑这个问题与视频的编码有关，

部分的播放器会有上述问题如：windows自带的media player、Chrome里面的播放器、iOS默认的播放器；

但VLC、potplayer等播放器可以正常播放。

**Comment by yajuhua** [comment]
## 改下编码试试
![image](https://github.com/user-attachments/assets/cb3baad0-2add-468b-9329-8f6f49100733)

**Comment by kennywhat** [comment]
这个是再哪里设置的？我在B站的插件那里没找到。

**Comment by yajuhua** [comment]
添加订阅的窗口，建议加一下群，这里回复麻烦。

**Comment by kennywhat** [comment]
哦，找到了，是在新添加订阅的时候。好的，我QQ电脑和手机上都太久没用，正在折腾升级。

**Comment by kennywhat** [comment]
感谢！按照这方法解决了！
