### ISSUE TITLE
Bilibili 下载失败，需要更新 yt-dlp 版本

### ISSUE THREAD

**Issue by mactavishmeng** [yajuhua/podcast2#21]
### 你必须先同意以下内容

- [X] 我已在 [Release](https://github.com/yajuhua/podcast2/releases) 检阅最新版本并尝试，且问题依旧
- [x] 我清楚知道，反馈非最新 Release 版的错误是无意义的
- [X] 我已查看 [文档](https://yajuhua.github.io/) ,但问题依旧。
- [X] 我清楚知道如何查看日志。
- [X] 我清楚知道不是我自己网络问题。

### Podcast2版本

v2.5.3

### 插件名称

yt-dlp

### 插件版本

2024.11.18

### 主页链接

None

### 错误描述

可能是近期的 Bilibili 页面更新，导致yt-dlp 在下载B站资源的时候会报错。

经过搜索和尝试，发现需要更新 yt-dlp，可按照 https://github.com/yt-dlp/yt-dlp/issues/11665#issuecomment-2505938652 所述方法，在容器中执行 `yt-dlp --update-to grqz/yt-dlp@ie/bilibili/pi_fallbk` 命令切换版本，切换后使用 `yt-dlp --version` 命令查看到的版本为 2024.11.28.115509。

更换版本后，可正常下载B站资源。

希望能在 Docker image 中更新。

### 报错日志以及其他描述（如果有）

```
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1B7BZYcEZG: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by yajuhua** [comment]
容器中yt-dlp是使用stable版本，目前stable最新版就是2024.11.18。目前只需将哔哩哔哩插件更新至2.4.3版本就可以正常下载了

**Comment by yajuhua** [comment]
可以考虑doker中使用nightly版本
