### ISSUE TITLE
无法下载YT

### ISSUE THREAD

**Issue by torinkan** [yajuhua/podcast2#23]
### 你必须先同意以下内容

- [X] 我已在 [Release](https://github.com/yajuhua/podcast2/releases) 检阅最新版本并尝试，且问题依旧
- [X] 我清楚知道，反馈非最新 Release 版的错误是无意义的
- [X] 我已查看 [文档](https://yajuhua.github.io/) ,但问题依旧。
- [X] 我清楚知道如何查看日志。
- [X] 我清楚知道不是我自己网络问题。

### Podcast2版本

v2.5.3

### 插件名称

youtube.com

### 插件版本

2.5.1

### 主页链接

https://www.youtube.com/@flipradio_fearnation

### 错误描述

在docker里面安装了V2RAYA之后，也使用你推荐的方法搭建了VLESS和代理，但是依旧无法在Podcast2里面下载YT. 报错如下

024-11-30 20:30:56.054 [pool-2942-thread-1] INFO i.g.yajuhua.podcast2.task.Update - 开始检查更新: FearNation 世界苦茶 - YouTube
2024-11-30 20:32:18.701 [pool-2942-thread-1] ERROR i.g.yajuhua.podcast2.task.Update - FearNation 世界苦茶 - YouTube:更新异常
java.lang.Exception: WARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ ssl.c:1006). Retrying (1/3)...WARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of pr otocol (_ssl.c:1006). Retrying (2/3)...WARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violat ion of protocol (_ssl.c:1006). Retrying (3/3)...WARNING: [youtube:tab] Unable to download webpage: [SSL: UNEXPECTED_EOF_ WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) (caused by SSLError('[SSL: UNEXPECTED_EOF_WHILE_READI NG] EOF occurred in violation of protocol (_ssl.c:1006)')); please report this issue on https://github.com/yt-dlp/yt-dl p/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U. Giving up after 3 retriesWARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ss l.c:1006). Retrying (1/3)...WARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of prot ocol (_ssl.c:1006). Retrying (2/3)...WARNING: [youtube:tab] [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violatio n of protocol (_ssl.c:1006). Retrying (3/3)...ERROR: [youtube:tab] @flipradio_fearnation: Unable to download API page: [ SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006) (caused by SSLError('[SSL: UNEXPE CTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')); please report this issue on https://git hub.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version usin g yt-dlp -U
at io.github.yajuhua.youtube.utils.CmdLineUtil.exec(CmdLineUtil.java:41)
at io.github.yajuhua.youtube.utils.CmdLineUtil.exec(CmdLineUtil.java:75)
at io.github.yajuhua.youtube.main.Main.items(Main.java:157)
at io.github.yajuhua.youtube.main.Main.latestItem(Main.java:167)
at io.github.yajuhua.podcast2.task.Update.run(Update.java:148)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

![image](https://github.com/user-attachments/assets/3be5cfa4-b7f9-493a-8725-bd8ce46446cd)
![image](https://github.com/user-attachments/assets/50738c91-2c35-467d-b07c-5e515dbc55a0)

**Comment by yajuhua** [comment]
我刚刚测试了你提供的链接没问题，可以下载最新一集。是不是网络没配置好？

**Comment by torinkan** [comment]
> 我刚刚测试了你提供的链接没问题，可以下载最新一集。是不是网络没配置好？

谢谢提醒，换了一个节点就可以了，大意了，我用的大陆白名单竟然用网易云音乐去测的代理。另外想请教一下，因为我podcast2和v2raya都装的一台机器上的，我在YT插件配置代理的地址，可不可是localhost 或者0.0.0.0加端口，还是说一定要写公网的IP

**Comment by yajuhua** [comment]
`localhost 或者0.0.0.0加端口`我没测试过你可以试试
