### ISSUE TITLE
订阅内容时间戳错误

### ISSUE THREAD

**Issue by torinkan** [yajuhua/podcast2#24]
### 你必须先同意以下内容

- [X] 我已在 [Release](https://github.com/yajuhua/podcast2/releases) 检阅最新版本并尝试，且问题依旧
- [X] 我清楚知道，反馈非最新 Release 版的错误是无意义的
- [X] 我已查看 [文档](https://yajuhua.github.io/) ,但问题依旧。
- [X] 我清楚知道如何查看日志。
- [X] 我清楚知道不是我自己网络问题。

### Podcast2版本

v2.5.3

### 插件名称

youtube.com

### 插件版本

2.5.1

### 主页链接

https://www.youtube.com/@flipradio_fearnation

### 错误描述

![image](https://github.com/user-attachments/assets/fb47d44d-8a97-4d63-97ac-b0cad62c3aea)

**Comment by yajuhua** [comment]
将插件更新至`2.5.2`即可，需要等下期节目更新或者追加节目才有效，`重新下载`是不会更新时间的。

**Comment by torinkan** [comment]
写错了，插件就是2.5.2

**Comment by yajuhua** [comment]
插件`2.5.2`是昨晚十点多才更新的，你可以追加一期节目看看时间是否正确。
