### ISSUE TITLE
bilibili下载的视频为mkv格式播客客户端没法直接播放能否指定下载mp4格式

### ISSUE THREAD

**Issue by yxjxx** [yajuhua/podcast2#25]
### 你必须先同意以下内容

- [X] 我已在 [Release](https://github.com/yajuhua/podcast2/releases) 检阅最新版本并尝试，且问题依旧
- [X] 我清楚知道，反馈非最新 Release 版的错误是无意义的
- [x] 我已查看 [文档](https://yajuhua.github.io/) ,但问题依旧。
- [X] 我清楚知道如何查看日志。
- [X] 我清楚知道不是我自己网络问题。

### Podcast2版本

2.5.3

### 插件名称

bilibili.com

### 插件版本

2.4.4

### 主页链接

任意

### 错误描述

mkv

**Comment by yajuhua** [comment]
一般播客是用来听的吧，看还是少数。

**Comment by yxjxx** [comment]
> 一般播客是用来听的吧，看还是少数。

视频播客会越来越流行

**Comment by yxjxx** [comment]
yt-dlp 添加一个 --merge-output-format mp4 参数应该就可以了

**Comment by yajuhua** [comment]
更新至2.4.5应该就可以了

**Comment by yxjxx** [comment]
> 更新至2.4.5应该就可以了

我升级后试了下好像还是有问题，视频确实是mp4格式了，但是全程黑屏。我自己先在本地搭建一个 yt-dlp 尝试出一个work的参数。

**Comment by yajuhua** [comment]
默认视频编码是`avc`有些设备可能播放不了，你点`更多选项`改成`H264`编码。#15
![image](https://github.com/user-attachments/assets/d9efa7c2-bc97-47c2-9a9e-8c7dc39e8f21)

**Comment by yxjxx** [comment]
> 默认视频编码是`avc`有些设备可能播放不了，你点`更多选项`改成`H264`编码。#15
> 
> ![image](https://github.com/user-attachments/assets/d9efa7c2-bc97-47c2-9a9e-8c7dc39e8f21)
> 
> 

h264 可以了👍

**Comment by yxjxx** [comment]
YouTube 视频下载也是 mkv 格式，希望支持 mp4 格式

**Comment by yxjxx** [comment]
再反馈一个重复下载的问题，看起来是只对最新一期进行了比对，如果up删除了最新一期会导致重复下载之前的一期
![image](https://github.com/user-attachments/assets/253745a5-16c6-4a66-aced-2fba140a9b39)

**Comment by yajuhua** [comment]
> YouTube 视频下载也是 mkv 格式，希望支持 mp4 格式

https://yajuhua.github.io/#/plugin-usage?id=mp4扩展名
