### ISSUE TITLE
套了一层caddy，无法添加新播客

### ISSUE THREAD

**Issue by konamichou** [yajuhua/podcast2#3]
通过套了一层caddy，实现https访问，无法添加新播客。
其他功能如下载feed、媒体文件、设置域名、修改用户信息等都可以正常工作，
就是点击添加订阅，理论上应该让填连接等等，实际情况是跳至登录界面。

**Comment by yajuhua** [comment]
套caddy应该不行，你可以通过crt和key来实现https。这个版本问题比较多，经常跳到登录界面。如果不影响使用的话，建议先http。目前已经在开发下个版本了，大概在还有半个月左右吧。

**Comment by yajuhua** [comment]
可查看文档设置https://yajuhua.github.io/#/advanced-application?id=caddy-%e5%bc%80%e5%90%af-https
