### ISSUE TITLE
密码修改问题

### ISSUE THREAD

**Issue by Felix2yu** [yajuhua/podcast2#5]
podcast2版本为2.0.3
密码如果设置为`1234-ABCD`会报错提示密码必须6-12位，如果把减号移动到最后`1234ABCD-`则可以正常修改正常登录。
密码如果设置为`Favoring-Perfume-Podcast`可以正常修改，但是登录的时候会报错提示用户名或密码错误。

**Comment by yajuhua** [comment]
目前最新镜像2.0.4应该解决了这个问题，可以试试

**Comment by Felix2yu** [comment]
使用`yajuhua/podcast2:v2.0.4-amd64`镜像后页面都无法显示，无论是映射出来的端口还是Nginx反向代理。

**Comment by yajuhua** [comment]
你把浏览器记录清空

**Comment by Felix2yu** [comment]
我用了两台电脑四个浏览器都是空白页，看响应内容为`We're sorry but Podcast2 doesn't work properly without JavaScript enabled. Please enable it to continue.`
但实际JavaScript是启用的，并且将镜像回退至`yajuhua/podcast2:v2.0.3-amd64`页面又能打开了。

**Comment by yajuhua** [comment]
你试一下yajuhua/podcast2:beta-2024-04-25

**Comment by Felix2yu** [comment]
这个镜像页面可以访问，但密码问题依旧，我尝试设置密码为`Ducktail-Squad6-Cramp`，提交修改的时候提示我密码必须6-12位

**Comment by yajuhua** [comment]
`Ducktail-Squad6-Cramp`已经是21位了，密码只能设置为6-12位

**Comment by Felix2yu** [comment]
我脑子抽了，没想到密码有上限还很低，没注意提示。
将密码设置为`-Excavator4#`后可以提交修改，但是重新登录的时候提示密码错误，将最后一位的#删除后能正常登录了，提交时把#丢了？

**Comment by yajuhua** [comment]
试一下`yajuhua/podcast2:beta-2024-04-26`

**Comment by Felix2yu** [comment]
可以了，感谢🙏
