### ISSUE TITLE
Youtube虽然指定下载数量，但是都只下载一集

### ISSUE THREAD

**Issue by torinkan** [yajuhua/podcast2#6]
RT, 

![image](https://github.com/yajuhua/podcast2/assets/13595721/205c5602-0ce6-4b5d-9523-bad4876210f1)
![image](https://github.com/yajuhua/podcast2/assets/13595721/2b52145f-a363-4ab0-a370-0fb4e749207c)

**Comment by yajuhua** [comment]
当前插件只能爬到最新一集，下个版本可能会更新

**Comment by yajuhua** [comment]
自定义是列表不是总数，如1,2,3会下载最近三集

**Comment by torinkan** [comment]
谢谢解答！

**Comment by yajuhua** [comment]
youtube插件2.0.3应该可以下载列表了，可以去试试。
