### ISSUE TITLE
youtube下载列表不是从最新一集开始下载

### ISSUE THREAD

**Issue by jp0id** [yajuhua/podcast2#7]
试了下载，都是从列表最旧的一集开始下载，不知道有什么配置可以改成下载列表中的最新的一集。

**Comment by yajuhua** [comment]
正常情况下应该是下载最新一集的，可以给我看看你的添加配置吗

**Comment by yajuhua** [comment]
我刚刚试了确实是有这个问题，可能明天会修复。

**Comment by yajuhua** [comment]
更新了youtube-2.0.4，可以去试试

**Comment by jp0id** [comment]
> 更新了youtube-2.0.4，可以去试试

好的，感谢。

**Comment by jp0id** [comment]
还是不行，下载的还是最老的一集。截图如下：

<img width="968" alt="截屏2024-05-22 15 05 16" src="https://github.com/yajuhua/podcast2/assets/35218851/4cc29f3a-1d70-4038-96d1-15ee4e59ed83">
<img width="1238" alt="截屏2024-05-22 15 05 43" src="https://github.com/yajuhua/podcast2/assets/35218851/507ece1e-7399-4c7a-a42f-dae9fd4ce263">
<img width="1465" alt="截屏2024-05-22 15 06 39" src="https://github.com/yajuhua/podcast2/assets/35218851/3f31dd66-5c27-4a00-ae83-581c01e8fa05">
<img width="1438" alt="截屏2024-05-22 15 06 48" src="https://github.com/yajuhua/podcast2/assets/35218851/47662581-2472-4672-a8b6-d66452fb689b">

**Comment by jp0id** [comment]
> 还是不行，下载的还是最老的一集。截图如下：
> 
> <img alt="截屏2024-05-22 15 05 16" width="968" src="https://private-user-images.githubusercontent.com/35218851/332694593-4cc29f3a-1d70-4038-96d1-15ee4e59ed83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjE5NzEsIm5iZiI6MTcxNjM2MTY3MSwicGF0aCI6Ii8zNTIxODg1MS8zMzI2OTQ1OTMtNGNjMjlmM2EtMWQ3MC00MDM4LTk2ZDEtMTVlZTRlNTllZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTczZDRhOTU2NDRiZDY0YTkzYTVhNDBmNjFiOTVmY2E2Njg3NDk3M2ZmY2VhOTcwNzEzNzQxNjI4NzFlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ajwG0Q7qDwEzgLDJoAAY0hyq-CDL0rgzbOSINkOfJKE"> <img alt="截屏2024-05-22 15 05 43" width="1238" src="https://private-user-images.githubusercontent.com/35218851/332694603-507ece1e-7399-4c7a-a42f-dae9fd4ce263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjE5NzEsIm5iZiI6MTcxNjM2MTY3MSwicGF0aCI6Ii8zNTIxODg1MS8zMzI2OTQ2MDMtNTA3ZWNlMWUtNzM5OS00YzdhLWE0MmYtZGFlOWZkNGNlMjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjdjYTExZjRkYzY2ZmIyNzQ3NThmNDI0YTQ2MWZiZDQ2NmU1OWUwZWUyYWQ2OGEyZTRkMWI1OTU0ODI1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnhFLwu6fOppYkrFb7MemCKScp5a7houMePEeQN7lCY"> <img alt="截屏2024-05-22 15 06 39" width="1465" src="https://private-user-images.githubusercontent.com/35218851/332694616-3f31dd66-5c27-4a00-ae83-581c01e8fa05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjE5NzEsIm5iZiI6MTcxNjM2MTY3MSwicGF0aCI6Ii8zNTIxODg1MS8zMzI2OTQ2MTYtM2YzMWRkNjYtNWMyNy00YTAwLWFlODMtNTgxYzAxZThmYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMTU0N2U5Zjg2YjU2MDBjNWM5ZGY1YTFiYWJiMTFiNjQwZDM3ZjIwZTk1ZTA1MjRmNzcwMGE3Yzc0YzZjYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tiyyhiYQuNDVo6XAhjVzSshhrlgg90PFX85NTbHpFUk"> <img alt="截屏2024-05-22 15 06 48" width="1438" src="https://private-user-images.githubusercontent.com/35218851/332694627-47662581-2472-4672-a8b6-d66452fb689b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjE5NzEsIm5iZiI6MTcxNjM2MTY3MSwicGF0aCI6Ii8zNTIxODg1MS8zMzI2OTQ2MjctNDc2NjI1ODEtMjQ3Mi00NjcyLWE4YjYtZDY2NDUyZmI2ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZGVjOGU3NTk5NmUzYWI3MGNlZTY3ZWMxNzVkZDcxMjFiYmIyYTA5ZDAwYzA1NDVmNzQyZDE4MjlkOGY4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPS-XlQV5dpRj2MW7RU6S9dR1AWFda7fVNhknL9pM2k">

视频列表中第一个应该是最新的视频。其它视频列表也是相同的情况。

**Comment by yajuhua** [comment]
![1](https://github.com/yajuhua/podcast2/assets/89304018/8542bd80-92a0-4aa2-84c0-3e3f291c1971)
![2](https://github.com/yajuhua/podcast2/assets/89304018/d95c8c97-8a00-4349-a49b-766098ee34e6)
你下载的确实是最新一集

**Comment by yajuhua** [comment]
YouTube视频列表有部分是第一个视频是最旧的，而最后应该才是最新的

**Comment by yajuhua** [comment]
你是想下载列表第一个视频？还是什么

**Comment by jp0id** [comment]
首先很感谢你的回复。

现在情况是这样的：
我订阅了一个yt列表，剧集选择了自定义：5
照理说应该会下载最新的5集，实际上只下载了最新的第5集，剩下的最新4集没有下载。

我订阅的地址：https://www.youtube.com/playlist?list=PLt2zGTMwV2dKZ562CGrbPsKyp6wLqvClC

<img width="964" alt="截屏2024-05-23 09 59 35" src="https://github.com/yajuhua/podcast2/assets/35218851/222b2264-9369-4f7b-819f-b11218005929">
实际下载的：
<img width="1383" alt="image" src="https://github.com/yajuhua/podcast2/assets/35218851/e3763640-a9dd-4aab-a5a0-348164f10d73">

如果订阅的时候选择最新的一集，现在确实是可以下载最新的。

**Comment by jp0id** [comment]
> 你是想下载列表第一个视频？还是什么

倒不是列表的第一个视频，而是时间上最新的视频。

**Comment by Jv0id** [comment]
刚才测了一下，选择最新的30集没有问题，目前看，应该是自定义集数那块儿有点问题。

**Comment by yajuhua** [comment]
看来这个选项容易误解，自定义剧集是视频列表，比如1,2,3,4,5会下载视频列表中序号为1-5的视频。
根据你提供的视频列表链接，如果你要下载最新5集，那么应该是1,2,3,4,5

**Comment by jp0id** [comment]
> 看来这个选项容易误解，自定义剧集是视频列表，比如1,2,3,4,5会下载视频列表中序号为1-5的视频。 根据你提供的视频列表链接，如果你要下载最新5集，那么应该是1,2,3,4,5

原来是这个意思，我一直以为是最新5集的意思。

**Comment by jp0id** [comment]
还有一个问题，选择最新30集，下载的也不是最新的30集，我刚才试了一下，好像是最老的30集。

**Comment by jp0id** [comment]
我重新试了下载，没有使用自定义，选择最新30集和最新1集，下载的依然是时间最久的视频。

**Comment by jp0id** [comment]
使用自定义：1，下载的是最新的一集了。
目前我的反馈是这样。我暂时先用自定义来订阅。

**Comment by yajuhua** [comment]
自定义剧集只是为了首次下载，第二次更新时会调用最新一集。这个[视频列表](https://www.youtube.com/watch?v=Q2uWaG1NHw0&list=PLB_lie3fxsanXrjcclfDQWXOO7Q4pvPmd)应该是没问题的

**Comment by jp0id** [comment]
好的，那最新一集和最新30集有点问题，你可以调试一下看看。

**Comment by yajuhua** [comment]
更新了youtube-2.0.5，可以去试试

**Comment by jp0id** [comment]
试了一下最近一集，没有问题了。
